#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "../Battle/HSRBattleCoordinator.h"
#include "../Equipment/HSREquipmentSubsystem.h"
#include "../Data/Definitions/HSREquipmentDefinition.h"
#include "../Data/Definitions/HSRItemDefinition.h"
#include "../Data/Definitions/HSRItemEquipmentMappingCatalog.h"
#include "../Inventory/HSRInventorySubsystem.h"
#include "../GAS/HSRAbilitySystemComponent.h"
#include "GameplayEffect.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSREquipmentProjectionTest,"HSR.Save.EquipmentProjection",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSREquipmentProjectionTest::RunTest(const FString&)
{
	UWorld* World=UWorld::CreateWorld(EWorldType::GamePreview,false);AActor* Owner=World->SpawnActor<AActor>();UHSRBattleCoordinator* C=NewObject<UHSRBattleCoordinator>();UHSRAbilitySystemComponent* ASC=NewObject<UHSRAbilitySystemComponent>(Owner);Owner->AddInstanceComponent(ASC);ASC->RegisterComponent();ASC->InitAbilityActorInfo(Owner,Owner);FHSRBattleParticipant P;P.ParticipantId=TEXT("Player");P.AbilitySystemComponent=ASC;C->SetPlayerCharacterDefinition(TEXT("Character.A"),nullptr);C->SetParticipantsForEquipmentProjectionDevelopmentTest({P});C->SetEquipmentGameplayEffect(UGameplayEffect::StaticClass());C->SetRelicSetGameplayEffect(UGameplayEffect::StaticClass());
	const FGuid CharacterGuid=HSRCharacterGuidFromProfileName(TEXT("Character.A"));FHSREquipmentRestoreState State;State.Revision=1;FHSREquipmentInstance Head;Head.InstanceId=FGuid(1,2,3,4);Head.DefinitionId=TEXT("Relic.Head");Head.Kind=EHSREquipmentKind::Relic;Head.Modifiers.Add({EHSREquipmentStat::Attack,10});FHSREquipmentInstance Hands=Head;Hands.InstanceId=FGuid(5,6,7,8);Hands.DefinitionId=TEXT("Relic.Hands");Hands.Modifiers[0].Value=4;State.Loadout.Relics.Add(EHSRRelicSlot::Head,Head);State.Loadout.Relics.Add(EHSRRelicSlot::Hands,Hands);State.RelicSetCounts.Add(TEXT("Set.A"),2);FHSREquipmentRestoreMap Candidate;Candidate.Add(CharacterGuid,State);
	TestTrue(TEXT("profile character projects to Player participant"),C->ProjectEquipmentRestore(Candidate));TestEqual(TEXT("two instances plus set source"),C->GetEquipmentProjectionSourceCountForDevelopmentTest(),3);TestTrue(TEXT("repeat succeeds"),C->ProjectEquipmentRestore(Candidate));TestEqual(TEXT("repeat no stack"),C->GetEquipmentProjectionSourceCountForDevelopmentTest(),3);
	FHSREquipmentRestoreState Reduced=State;Reduced.Revision=2;Reduced.Loadout.Relics.Remove(EHSRRelicSlot::Hands);Reduced.RelicSetCounts[TEXT("Set.A")]=1;Candidate[CharacterGuid]=Reduced;C->SetEquipmentRestoreProjectionFailureAfterOperationsForDevelopmentTest(1);AddExpectedError(TEXT("HSR.EquipmentProjection FAIL"),EAutomationExpectedErrorFlags::Contains,1);TestFalse(TEXT("mid-transaction failure"),C->ProjectEquipmentRestore(Candidate));TestEqual(TEXT("all old sources restored"),C->GetEquipmentProjectionSourceCountForDevelopmentTest(),3);C->SetEquipmentRestoreProjectionFailureAfterOperationsForDevelopmentTest(-1);TestTrue(TEXT("single relic and set removal succeed"),C->ProjectEquipmentRestore(Candidate));TestEqual(TEXT("only retained relic remains"),C->GetEquipmentProjectionSourceCountForDevelopmentTest(),1);World->DestroyWorld(false);return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSREquipmentMovementRuntimeProjectionTest,"HSR.Equipment.Movement.RuntimeProjection",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSREquipmentMovementRuntimeProjectionTest::RunTest(const FString&)
{
	UWorld* World=UWorld::CreateWorld(EWorldType::GamePreview,false);AActor* Owner=World->SpawnActor<AActor>();UHSRAbilitySystemComponent* ASC=NewObject<UHSRAbilitySystemComponent>(Owner);Owner->AddInstanceComponent(ASC);ASC->RegisterComponent();ASC->InitAbilityActorInfo(Owner,Owner);UHSRBattleCoordinator* Coordinator=NewObject<UHSRBattleCoordinator>();FHSRBattleParticipant Participant;Participant.ParticipantId=TEXT("Player");Participant.AbilitySystemComponent=ASC;Coordinator->SetPlayerCharacterDefinition(TEXT("Character.A"),nullptr);Coordinator->SetParticipantsForEquipmentProjectionDevelopmentTest({Participant});
	UGameInstance* GameInstance=NewObject<UGameInstance>();UHSRInventorySubsystem* Inventory=NewObject<UHSRInventorySubsystem>(GameInstance);UHSREquipmentSubsystem* Equipment=NewObject<UHSREquipmentSubsystem>(GameInstance);UHSRItemEquipmentMappingCatalog* Catalog=NewObject<UHSRItemEquipmentMappingCatalog>();UHSRItemDefinition* Item=NewObject<UHSRItemDefinition>();Item->ItemId=TEXT("Item.Weapon");Item->StorageKind=EHSRItemStorageKind::Unique;Item->MaxStack=1;TestEqual(TEXT("item definition"),Inventory->RegisterDefinition(*Item),EHSRInventoryOperationResult::Success);UHSREquipmentDefinition* Definition=NewObject<UHSREquipmentDefinition>();Definition->DefinitionId=TEXT("Equipment.Weapon");Definition->Slot=EHSREquipmentSlot::Weapon;TestEqual(TEXT("equipment definition"),Equipment->RegisterDefinition(*Definition),EHSREquipmentOperationResult::Success);FHSRItemEquipmentMappingEntry Mapping;Mapping.ItemId=Item->ItemId;Mapping.EquipmentDefinitionId=Definition->DefinitionId;Mapping.Kind=EHSREquipmentKind::Equipment;Mapping.Slot=static_cast<int32>(EHSREquipmentSlot::Weapon);TestTrue(TEXT("mapping"),Catalog->AddMapping(Mapping));
	const FGuid InstanceId=FGuid::NewGuid();FHSRItemInstance Bagged;Bagged.InstanceId=InstanceId;Bagged.DefinitionId=Item->ItemId;TestEqual(TEXT("bagged"),Inventory->AddUnique(Bagged),EHSRInventoryOperationResult::Success);FHSREquipmentInstance Registered;Registered.InstanceId=InstanceId;Registered.DefinitionId=Definition->DefinitionId;Registered.Kind=EHSREquipmentKind::Equipment;TestEqual(TEXT("registered"),Equipment->RegisterInstance(Registered),EHSREquipmentOperationResult::Success);FHSRInventorySnapshot Before;Inventory->GetSnapshot(Before);FHSREquipmentMovementRequest Request;Request.OperationId=FGuid::NewGuid();Request.CharacterId=HSRCharacterGuidFromProfileName(TEXT("Character.A"));Request.InstanceId=InstanceId;Request.Intent=EHSREquipmentMovementIntent::Equip;Request.Kind=EHSREquipmentKind::Equipment;Request.Slot=static_cast<int32>(EHSREquipmentSlot::Weapon);Request.ExpectedInventoryRevision=Before.Revision;
	Coordinator->BindEquipmentMovementProjection(*Equipment);TestEqual(TEXT("missing effect rejects before movement"),Equipment->ExecuteMovement(Request,*Inventory,*Catalog).Code,EHSREquipmentMovementResultCode::ProjectionRejected);Inventory->GetSnapshot(Before);TestEqual(TEXT("rejected movement preserves bag"),Before.UniqueItems.Num(),1);Coordinator->SetEquipmentGameplayEffect(UGameplayEffect::StaticClass());Request.OperationId=FGuid::NewGuid();const FHSREquipmentMovementResult EquipResult=Equipment->ExecuteMovement(Request,*Inventory,*Catalog);TestEqual(TEXT("bound runtime projection commits"),EquipResult.Code,EHSREquipmentMovementResultCode::Success);TestEqual(TEXT("one runtime source"),Coordinator->GetEquipmentProjectionSourceCountForDevelopmentTest(),1);
	FHSREquipmentMovementRequest Unequip=Request;Unequip.OperationId=FGuid::NewGuid();Unequip.Intent=EHSREquipmentMovementIntent::Unequip;Unequip.ExpectedInventoryRevision=EquipResult.NewInventoryRevision;Unequip.ExpectedEquipmentRevision=EquipResult.NewEquipmentRevision;TestEqual(TEXT("runtime unequip commits"),Equipment->ExecuteMovement(Unequip,*Inventory,*Catalog).Code,EHSREquipmentMovementResultCode::Success);TestEqual(TEXT("runtime unequip removes source"),Coordinator->GetEquipmentProjectionSourceCountForDevelopmentTest(),0);World->DestroyWorld(false);return true;
}
#endif
