#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Engine/GameInstance.h"
#include "Curves/CurveFloat.h"
#include "Kismet/GameplayStatics.h"
#include "../Data/Definitions/HSRCharacterDefinition.h"
#include "../Progression/HSRCharacterProfileSubsystem.h"
#include "../Party/HSRPartySubsystem.h"
#include "../Equipment/HSREquipmentSubsystem.h"
#include "../Save/HSRSaveSubsystem.h"
#include "../Save/HSRSaveVersion.h"

namespace
{
struct FP16WriteFixture
{
	UGameInstance* GI=NewObject<UGameInstance>();
	UHSRCharacterProfileSubsystem* Profiles=NewObject<UHSRCharacterProfileSubsystem>(GI);
	UHSRPartySubsystem* Party=NewObject<UHSRPartySubsystem>(GI);
	UHSREquipmentSubsystem* Equipment=NewObject<UHSREquipmentSubsystem>(GI);
	UHSRSaveSubsystem* Save=NewObject<UHSRSaveSubsystem>(GI);
	FP16WriteFixture()
	{
		UHSRCharacterDefinition* Definition=NewObject<UHSRCharacterDefinition>();Definition->CharacterId=TEXT("character.p16");Definition->MaxLevel=2;UCurveFloat* Curve=NewObject<UCurveFloat>(Definition);Curve->FloatCurve.AddKey(2,100);Definition->CumulativeExperienceCurve=Curve;Profiles->RegisterDefinition(Definition);Party->InitializeForDevelopmentTest(Profiles);Party->AddCharacter(Definition->CharacterId);Save->InitializeForDevelopmentTest(Profiles,Party,Equipment);
	}
};
FString Role(const FString& Base,const TCHAR* Suffix){return Base+Suffix;}
void Cleanup(const FString& Base){UGameplayStatics::DeleteGameInSlot(Base,0);UGameplayStatics::DeleteGameInSlot(Role(Base,TEXT(".__hsr_staging_v1")),0);UGameplayStatics::DeleteGameInSlot(Role(Base,TEXT(".__hsr_backup_v1")),0);}
bool ReadHeader(const FString& Physical,const FString& Logical,FHSRSaveEnvelopeHeader& Header,TArray<uint8>* OutBytes=nullptr){TArray<uint8> Bytes;FHSRSaveData Data;if(!UGameplayStatics::LoadDataFromSlot(Bytes,Physical,0)||HSRSaveVersion::DecodeEnvelope(Bytes,Logical,0,Data,&Header)!=EHSRSaveDecodeResult::Success)return false;if(OutBytes)*OutBytes=MoveTemp(Bytes);return true;}
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveWriteTransactionTest,"HSR.Save.WriteTransaction",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSRSaveWriteTransactionTest::RunTest(const FString&)
{
	FP16WriteFixture F;const FString Base=FString::Printf(TEXT("p16_tx_%s"),*FGuid::NewGuid().ToString(EGuidFormats::Digits));Cleanup(Base);
	const EHSRSaveResult FirstResult=F.Save->SaveToSlot(Base);TestEqual(TEXT("first save result code"),static_cast<int32>(FirstResult),static_cast<int32>(EHSRSaveResult::Success));TestEqual(TEXT("first save failure stage code"),static_cast<int32>(F.Save->GetLastWriteFailureStage()),static_cast<int32>(EHSRSaveFailureStage::None));FHSRSaveEnvelopeHeader P1;TArray<uint8> P1Bytes;TestTrue(TEXT("primary gen1 readable"),ReadHeader(Base,Base,P1,&P1Bytes));TestEqual(TEXT("first generation"),P1.Generation,static_cast<uint64>(1));TestFalse(TEXT("first staging cleaned"),UGameplayStatics::DoesSaveGameExist(Role(Base,TEXT(".__hsr_staging_v1")),0));
	TestEqual(TEXT("second save"),F.Save->SaveToSlot(Base),EHSRSaveResult::Success);FHSRSaveEnvelopeHeader P2,B1;TestTrue(TEXT("primary gen2 readable"),ReadHeader(Base,Base,P2));TestTrue(TEXT("backup gen1 readable"),ReadHeader(Role(Base,TEXT(".__hsr_backup_v1")),Base,B1));TestTrue(TEXT("lineage stable"),P1.SaveId==P2.SaveId&&P1.SaveId==B1.SaveId);TestEqual(TEXT("generation increments"),P2.Generation,static_cast<uint64>(2));TestEqual(TEXT("backup preserves previous"),B1.Generation,static_cast<uint64>(1));Cleanup(Base);
	const FString DamagedBase=Base+TEXT("_damaged");Cleanup(DamagedBase);TestEqual(TEXT("damaged seed one"),F.Save->SaveToSlot(DamagedBase),EHSRSaveResult::Success);TestEqual(TEXT("damaged seed two"),F.Save->SaveToSlot(DamagedBase),EHSRSaveResult::Success);FHSRSaveEnvelopeHeader GoodBackup;TArray<uint8> GoodBackupBytes;TestTrue(TEXT("good backup before corruption"),ReadHeader(Role(DamagedBase,TEXT(".__hsr_backup_v1")),DamagedBase,GoodBackup,&GoodBackupBytes));TArray<uint8> CorruptPrimary={'b','a','d'};TestTrue(TEXT("write controlled corrupt primary"),UGameplayStatics::SaveDataToSlot(CorruptPrimary,DamagedBase,0));TestEqual(TEXT("save advances from trusted backup"),F.Save->SaveToSlot(DamagedBase),EHSRSaveResult::Success);FHSRSaveEnvelopeHeader RebuiltPrimary,PreservedBackup;TArray<uint8> PreservedBackupBytes;TestTrue(TEXT("rebuilt primary readable"),ReadHeader(DamagedBase,DamagedBase,RebuiltPrimary));TestTrue(TEXT("good backup remains readable"),ReadHeader(Role(DamagedBase,TEXT(".__hsr_backup_v1")),DamagedBase,PreservedBackup,&PreservedBackupBytes));TestTrue(TEXT("bad primary did not overwrite backup"),GoodBackupBytes==PreservedBackupBytes);TestTrue(TEXT("backup lineage reused"),RebuiltPrimary.SaveId==GoodBackup.SaveId&&RebuiltPrimary.Generation==GoodBackup.Generation+1);TestEqual(TEXT("reserved role collision rejected"),F.Save->SaveToSlot(DamagedBase+TEXT(".__hsr_backup_v1")),EHSRSaveResult::InvalidArgument);Cleanup(DamagedBase);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveWriteFailureMatrixTest,"HSR.Save.WriteFailureMatrix",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSRSaveWriteFailureMatrixTest::RunTest(const FString&)
{
	FP16WriteFixture F;const TArray<EHSRSaveFailureStage> BeforePrimary={EHSRSaveFailureStage::Capture,EHSRSaveFailureStage::Encode,EHSRSaveFailureStage::StagingWrite,EHSRSaveFailureStage::StagingReadback,EHSRSaveFailureStage::BackupWrite,EHSRSaveFailureStage::BackupReadback,EHSRSaveFailureStage::PrimaryWrite};
	for(const EHSRSaveFailureStage Stage:BeforePrimary){const FString Base=FString::Printf(TEXT("p16_fail_%d_%s"),static_cast<int32>(Stage),*FGuid::NewGuid().ToString(EGuidFormats::Digits));Cleanup(Base);F.Save->SetTransactionFailureInjection(EHSRSaveFailureStage::None);TestEqual(TEXT("seed primary"),F.Save->SaveToSlot(Base),EHSRSaveResult::Success);TArray<uint8> Before;FHSRSaveEnvelopeHeader Header;TestTrue(TEXT("seed readable"),ReadHeader(Base,Base,Header,&Before));const FHSRSaveData CurrentBefore=F.Save->GetSnapshot();F.Save->SetTransactionFailureInjection(Stage);TestTrue(TEXT("injected failure"),F.Save->SaveToSlot(Base)!=EHSRSaveResult::Success);TestEqual(TEXT("diagnostic stage"),F.Save->GetLastWriteFailureStage(),Stage);TArray<uint8> After;TestTrue(TEXT("old primary still readable"),ReadHeader(Base,Base,Header,&After));TestTrue(TEXT("old primary byte exact"),Before==After);TestEqual(TEXT("Current preserved"),F.Save->GetSnapshot().PartyRevision,CurrentBefore.PartyRevision);Cleanup(Base);}
	{
		const FString Base=FString::Printf(TEXT("p16_primary_read_%s"),*FGuid::NewGuid().ToString(EGuidFormats::Digits));Cleanup(Base);F.Save->SetTransactionFailureInjection(EHSRSaveFailureStage::None);TestEqual(TEXT("seed for primary read"),F.Save->SaveToSlot(Base),EHSRSaveResult::Success);F.Save->SetTransactionFailureInjection(EHSRSaveFailureStage::PrimaryReadback);TestEqual(TEXT("primary readback injected"),F.Save->SaveToSlot(Base),EHSRSaveResult::LoadFailed);FHSRSaveEnvelopeHeader Backup,Staging;TestTrue(TEXT("backup retained"),ReadHeader(Role(Base,TEXT(".__hsr_backup_v1")),Base,Backup));TestTrue(TEXT("staging retained"),ReadHeader(Role(Base,TEXT(".__hsr_staging_v1")),Base,Staging));TestTrue(TEXT("staging newer than backup"),Staging.SaveId==Backup.SaveId&&Staging.Generation>Backup.Generation);Cleanup(Base);
	}
	{
		const FString Base=FString::Printf(TEXT("p16_cleanup_%s"),*FGuid::NewGuid().ToString(EGuidFormats::Digits));Cleanup(Base);F.Save->SetTransactionFailureInjection(EHSRSaveFailureStage::Cleanup);TestEqual(TEXT("cleanup warning is committed success"),F.Save->SaveToSlot(Base),EHSRSaveResult::Success);TestTrue(TEXT("cleanup warning diagnostic"),F.Save->HadLastWriteCleanupWarning());TestTrue(TEXT("staging retained for retry"),UGameplayStatics::DoesSaveGameExist(Role(Base,TEXT(".__hsr_staging_v1")),0));FHSRSaveEnvelopeHeader Primary;TestTrue(TEXT("primary committed despite cleanup"),ReadHeader(Base,Base,Primary));Cleanup(Base);
	}
	F.Save->SetTransactionFailureInjection(EHSRSaveFailureStage::None);return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveLoadRecoveryTest,"HSR.Save.LoadRecovery",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSRSaveLoadRecoveryTest::RunTest(const FString&)
{
	FP16WriteFixture F;const FString Base=FString::Printf(TEXT("p16_recover_%s"),*FGuid::NewGuid().ToString(EGuidFormats::Digits));const FString BackupSlot=Role(Base,TEXT(".__hsr_backup_v1"));Cleanup(Base);TestEqual(TEXT("seed primary one"),F.Save->SaveToSlot(Base),EHSRSaveResult::Success);TestEqual(TEXT("seed primary two"),F.Save->SaveToSlot(Base),EHSRSaveResult::Success);
	TestEqual(TEXT("valid primary preferred"),F.Save->LoadFromSlot(Base),EHSRSaveResult::Success);TestEqual(TEXT("primary source"),F.Save->GetLastLoadResult().Source,EHSRSaveLoadSource::Primary);const int64 RepeatTx=F.Save->GetRestoreTransactionRevisionForDevelopmentTest();TestEqual(TEXT("repeat primary load"),F.Save->LoadFromSlot(Base),EHSRSaveResult::Success);TestEqual(TEXT("repeat load no-op tx"),F.Save->GetRestoreTransactionRevisionForDevelopmentTest(),RepeatTx);
	TArray<uint8> PrimaryBefore,BackupBefore;TestTrue(TEXT("read primary before corruption"),UGameplayStatics::LoadDataFromSlot(PrimaryBefore,Base,0));TestTrue(TEXT("read backup before recovery"),UGameplayStatics::LoadDataFromSlot(BackupBefore,BackupSlot,0));TArray<uint8> Corrupt={'x'};TestTrue(TEXT("corrupt primary"),UGameplayStatics::SaveDataToSlot(Corrupt,Base,0));TArray<uint8> CorruptBefore;UGameplayStatics::LoadDataFromSlot(CorruptBefore,Base,0);TestEqual(TEXT("backup recovery"),F.Save->LoadFromSlot(Base),EHSRSaveResult::Success);TestEqual(TEXT("backup source"),F.Save->GetLastLoadResult().Source,EHSRSaveLoadSource::Backup);TestTrue(TEXT("primary marked untrusted"),F.Save->GetLastLoadResult().bPrimaryUntrusted);TArray<uint8> CorruptAfter,BackupAfter;UGameplayStatics::LoadDataFromSlot(CorruptAfter,Base,0);UGameplayStatics::LoadDataFromSlot(BackupAfter,BackupSlot,0);TestTrue(TEXT("recovery never repairs primary"),CorruptAfter==CorruptBefore);TestTrue(TEXT("recovery never rewrites backup"),BackupAfter==BackupBefore);
	FHSRSaveData BackupData;FHSRSaveEnvelopeHeader BackupHeader;TestEqual(TEXT("decode backup fixture"),HSRSaveVersion::DecodeEnvelope(BackupBefore,Base,0,BackupData,&BackupHeader),EHSRSaveDecodeResult::Success);FHSRSaveData FutureData=BackupData;FutureData.SchemaVersion=7;TArray<uint8> FuturePrimary;TestTrue(TEXT("encode trusted future primary"),HSRSaveVersion::EncodeEnvelopeAtUtc(FutureData,Base,0,BackupHeader.SaveId,BackupHeader.Generation+1,123,FuturePrimary));TestTrue(TEXT("write future primary"),UGameplayStatics::SaveDataToSlot(FuturePrimary,Base,0));TestEqual(TEXT("future primary uses compatible backup"),F.Save->LoadFromSlot(Base),EHSRSaveResult::Success);TestEqual(TEXT("future recovery source"),F.Save->GetLastLoadResult().Source,EHSRSaveLoadSource::Backup);TestTrue(TEXT("future header trusted"),F.Save->GetLastLoadResult().bPrimaryHeaderTrusted);
	FHSRSaveData MissingDefinition=BackupData;FHSRItemStackSnapshot MissingItem;MissingItem.ItemId=TEXT("missing.p16.item");MissingItem.Quantity=1;MissingDefinition.Inventory.Stacks.Add(MissingItem);TArray<uint8> InvalidPrimary;TestTrue(TEXT("encode definition-invalid primary"),HSRSaveVersion::EncodeEnvelopeAtUtc(MissingDefinition,Base,0,BackupHeader.SaveId,BackupHeader.Generation+1,124,InvalidPrimary));UGameplayStatics::SaveDataToSlot(InvalidPrimary,Base,0);TestEqual(TEXT("prepare-invalid primary uses backup"),F.Save->LoadFromSlot(Base),EHSRSaveResult::Success);TestEqual(TEXT("prepare fallback source"),F.Save->GetLastLoadResult().Source,EHSRSaveLoadSource::Backup);TestEqual(TEXT("primary prepare reason"),F.Save->GetLastLoadResult().PrimaryStageReason,EHSRSaveLoadReason::PrepareFailed);
	TArray<uint8> ValidPrimary;TestTrue(TEXT("encode valid primary for projection"),HSRSaveVersion::EncodeEnvelopeAtUtc(BackupData,Base,0,BackupHeader.SaveId,BackupHeader.Generation+1,125,ValidPrimary));UGameplayStatics::SaveDataToSlot(ValidPrimary,Base,0);int32 ProjectionCalls=0;F.Equipment->SetRestoreProjection(FHSREquipmentRestoreProjection::CreateLambda([&](const FHSREquipmentRestoreMap&){++ProjectionCalls;return false;}));TestEqual(TEXT("selected primary projection failure"),F.Save->LoadFromSlot(Base),EHSRSaveResult::InvalidData);TestEqual(TEXT("projection failure remains primary"),F.Save->GetLastLoadResult().Source,EHSRSaveLoadSource::Primary);TestEqual(TEXT("projection only once"),ProjectionCalls,1);F.Equipment->SetRestoreProjection(FHSREquipmentRestoreProjection());
	UGameplayStatics::SaveDataToSlot(FuturePrimary,Base,0);TArray<uint8> WrongLineage;TestTrue(TEXT("encode wrong-lineage backup"),HSRSaveVersion::EncodeEnvelopeAtUtc(BackupData,Base,0,FGuid(99,1,1,1),1,124,WrongLineage));TestTrue(TEXT("write wrong-lineage backup"),UGameplayStatics::SaveDataToSlot(WrongLineage,BackupSlot,0));TestEqual(TEXT("lineage mismatch rejected"),F.Save->LoadFromSlot(Base),EHSRSaveResult::InvalidEnvelope);TestEqual(TEXT("lineage reason"),F.Save->GetLastLoadResult().BackupStageReason,EHSRSaveLoadReason::LineageMismatch);
	UGameplayStatics::SaveDataToSlot(FuturePrimary,Base,0);TArray<uint8> InvalidGeneration;TestTrue(TEXT("encode invalid-generation backup"),HSRSaveVersion::EncodeEnvelopeAtUtc(BackupData,Base,0,BackupHeader.SaveId,BackupHeader.Generation+1,125,InvalidGeneration));UGameplayStatics::SaveDataToSlot(InvalidGeneration,BackupSlot,0);TestEqual(TEXT("generation relation rejected"),F.Save->LoadFromSlot(Base),EHSRSaveResult::InvalidEnvelope);TestEqual(TEXT("generation reason"),F.Save->GetLastLoadResult().BackupStageReason,EHSRSaveLoadReason::InvalidGeneration);
	UGameplayStatics::SaveDataToSlot(Corrupt,Base,0);UGameplayStatics::SaveDataToSlot(Corrupt,BackupSlot,0);const FHSRSaveData CurrentBefore=F.Save->GetSnapshot();TestEqual(TEXT("double corrupt rejected"),F.Save->LoadFromSlot(Base),EHSRSaveResult::InvalidEnvelope);TestEqual(TEXT("double corrupt current preserved"),F.Save->GetSnapshot().PartyRevision,CurrentBefore.PartyRevision);
	F.Save->SetOperationBusyForAutomation(true);TestEqual(TEXT("busy rejected"),F.Save->LoadFromSlot(Base),EHSRSaveResult::InvalidArgument);TestEqual(TEXT("busy reason"),F.Save->GetLastLoadResult().PrimaryStageReason,EHSRSaveLoadReason::Busy);F.Save->SetOperationBusyForAutomation(false);F.Save->SetRestoreBlockedForAutomation(true,false);TestEqual(TEXT("map travel pending rejected"),F.Save->LoadFromSlot(Base),EHSRSaveResult::InvalidData);F.Save->SetRestoreBlockedForAutomation(false,true);TestEqual(TEXT("battle return pending rejected"),F.Save->LoadFromSlot(Base),EHSRSaveResult::InvalidData);F.Save->SetRestoreBlockedForAutomation(false,false);TestEqual(TEXT("reserved load role rejected"),F.Save->LoadFromSlot(BackupSlot),EHSRSaveResult::InvalidArgument);Cleanup(Base);return true;
}
#endif
