#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Engine/GameInstance.h"
#include "Curves/CurveFloat.h"
#include "../Data/Definitions/HSRCharacterDefinition.h"
#include "../Progression/HSRCharacterProfileSubsystem.h"
#include "../Party/HSRPartySubsystem.h"
#include "../Equipment/HSREquipmentSubsystem.h"
#include "../Save/HSRSaveSubsystem.h"
#include "../Save/HSRSaveGame.h"
#include "Kismet/GameplayStatics.h"
#include "Misc/ScopeExit.h"
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveSubsystemTest,"HSR.Save.V1",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSRSaveSubsystemTest::RunTest(const FString&)
{
	UGameInstance* GI=NewObject<UGameInstance>();auto* Profiles=NewObject<UHSRCharacterProfileSubsystem>(GI);auto* Party=NewObject<UHSRPartySubsystem>(GI);auto* Save=NewObject<UHSRSaveSubsystem>(GI);auto* Equipment=NewObject<UHSREquipmentSubsystem>(GI);
	auto MakeDef=[](FName Id){auto* D=NewObject<UHSRCharacterDefinition>();D->CharacterId=Id;D->MaxLevel=2;auto* C=NewObject<UCurveFloat>(D);C->FloatCurve.AddKey(2,100);D->CumulativeExperienceCurve=C;return D;};auto* B=MakeDef(TEXT("B"));auto* A=MakeDef(TEXT("A"));Profiles->RegisterDefinition(B);Profiles->RegisterDefinition(A);Party->InitializeForDevelopmentTest(Profiles);Save->InitializeForDevelopmentTest(Profiles,Party,Equipment);Party->AddCharacter(TEXT("A"));
	FHSRSaveData Captured;TestEqual(TEXT("capture"),Save->SaveSnapshot(Captured),EHSRSaveResult::Success);int32 RestoreEvents=0;Save->OnRestoreCommitted().AddLambda([&](const FHSRRestoreCommitInfo& Info){++RestoreEvents;TestEqual(TEXT("transaction revision"),Info.TransactionRevision,static_cast<int64>(1));});TestEqual(TEXT("nochange load"),Save->LoadSnapshot(Captured),EHSRSaveResult::Success);TestEqual(TEXT("nochange zero"),RestoreEvents,0);TestEqual(TEXT("stable A first"),Captured.Profiles[0].State.CharacterId,FName(TEXT("A")));TestEqual(TEXT("revision frozen"),Captured.Profiles[0].RuntimeRevision,static_cast<int64>(0));
	Profiles->GrantExperience(TEXT("A"),100);Party->ReplaceCharacter(0,TEXT("B"));int32 ProfileEvents=0,PartyEvents=0;bool ObserverAtomic=true;auto Observe=[&](){FHSRCharacterProfileSnapshot P;FHSRPartySnapshot Q;Profiles->GetProfileSnapshot(TEXT("A"),P);Party->GetSnapshot(Q);ObserverAtomic&=P.RuntimeState.Experience==0&&Q.Slots[0].CharacterId==TEXT("A")&&Save->GetSnapshot().PartySlots[0].CharacterId==TEXT("A");};Profiles->OnProfileChanged().AddLambda([&](FName,int64){++ProfileEvents;Observe();});Party->OnPartyChanged().AddLambda([&](int64){++PartyEvents;Observe();});
	TestEqual(TEXT("restore"),Save->LoadSnapshot(Captured),EHSRSaveResult::Success);TestEqual(TEXT("change emits once"),RestoreEvents,1);FHSRCharacterProfileSnapshot AP;Profiles->GetProfileSnapshot(TEXT("A"),AP);FHSRPartySnapshot PS;Party->GetSnapshot(PS);TestEqual(TEXT("profile restored"),AP.RuntimeState.Experience,0);TestEqual(TEXT("party restored"),PS.Slots[0].CharacterId,FName(TEXT("A")));const int32 PE=ProfileEvents,QE=PartyEvents;TestEqual(TEXT("same load no-op"),Save->LoadSnapshot(Captured),EHSRSaveResult::Success);TestEqual(TEXT("repeat still one"),RestoreEvents,1);TestEqual(TEXT("no profile event"),ProfileEvents,PE);TestEqual(TEXT("no party event"),PartyEvents,QE);
	FHSRSaveData Bad=Captured;Bad.Profiles[0].State.Experience=-1;TestEqual(TEXT("bad rejected"),Save->LoadSnapshot(Bad),EHSRSaveResult::InvalidData);Profiles->GetProfileSnapshot(TEXT("A"),AP);Party->GetSnapshot(PS);TestEqual(TEXT("failure profile unchanged"),AP.RuntimeState.Experience,0);TestEqual(TEXT("failure party unchanged"),PS.Slots[0].CharacterId,FName(TEXT("A")));Bad=Captured;{const FHSRSaveProfileDto Duplicate=Bad.Profiles[0];Bad.Profiles.Add(Duplicate);}TestEqual(TEXT("duplicate rejected"),Save->LoadSnapshot(Bad),EHSRSaveResult::InvalidData);Bad=Captured;Bad.PartySlots[1].CharacterId=TEXT("Unknown");TestEqual(TEXT("unknown rejected"),Save->LoadSnapshot(Bad),EHSRSaveResult::InvalidData);Bad=Captured;Bad.SchemaVersion=5;TestEqual(TEXT("unknown schema rejected"),Save->LoadSnapshot(Bad),EHSRSaveResult::UnsupportedSchema);TestTrue(TEXT("observer atomic"),ObserverAtomic);TestEqual(TEXT("profile event exactly once"),ProfileEvents,1);TestEqual(TEXT("party event exactly once"),PartyEvents,1);TestEqual(TEXT("failure current unchanged"),Save->GetSnapshot().PartyRevision,Captured.PartyRevision);TestEqual(TEXT("failure current profile unchanged"),Save->GetSnapshot().Profiles[0].State.Experience,Captured.Profiles[0].State.Experience);return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveDiskTest,"HSR.Save.DiskV1",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSRSaveDiskTest::RunTest(const FString&)
{
	const FString Slot=FString::Printf(TEXT("HSR_P11_%s"),*FGuid::NewGuid().ToString(EGuidFormats::Digits));const int32 User=0;UGameplayStatics::DeleteGameInSlot(Slot,User);
	UGameInstance* GI=NewObject<UGameInstance>();auto* Profiles=NewObject<UHSRCharacterProfileSubsystem>(GI);auto* Party=NewObject<UHSRPartySubsystem>(GI);auto* Save=NewObject<UHSRSaveSubsystem>(GI);auto* Equipment=NewObject<UHSREquipmentSubsystem>(GI);auto* D=NewObject<UHSRCharacterDefinition>();D->CharacterId=TEXT("A");D->MaxLevel=2;auto* C=NewObject<UCurveFloat>(D);C->FloatCurve.AddKey(2,100);D->CumulativeExperienceCurve=C;Profiles->RegisterDefinition(D);Party->InitializeForDevelopmentTest(Profiles);Save->InitializeForDevelopmentTest(Profiles,Party,Equipment);Party->AddCharacter(TEXT("A"));
	TestEqual(TEXT("empty argument"),Save->SaveToSlot(TEXT(""),User),EHSRSaveResult::InvalidArgument);TestEqual(TEXT("missing"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::SlotNotFound);TestEqual(TEXT("save"),Save->SaveToSlot(Slot,User),EHSRSaveResult::Success);Profiles->GrantExperience(TEXT("A"),100);Party->RemoveCharacter(0);TestEqual(TEXT("roundtrip"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::Success);FHSRCharacterProfileSnapshot P;FHSRPartySnapshot Q;Profiles->GetProfileSnapshot(TEXT("A"),P);Party->GetSnapshot(Q);TestEqual(TEXT("disk profile restored"),P.RuntimeState.Experience,0);TestEqual(TEXT("disk party restored"),Q.Slots[0].CharacterId,FName(TEXT("A")));
	USaveGame* Wrong=UGameplayStatics::CreateSaveGameObject(UHSRForeignSaveGame::StaticClass());TestTrue(TEXT("write mismatch"),UGameplayStatics::SaveGameToSlot(Wrong,Slot,User));TestEqual(TEXT("class mismatch"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::ClassMismatch);UHSRSaveGame* Bad=Cast<UHSRSaveGame>(UGameplayStatics::CreateSaveGameObject(UHSRSaveGame::StaticClass()));Bad->Data=Save->GetSnapshot();Bad->Data.SchemaVersion=5;TestTrue(TEXT("write schema"),UGameplayStatics::SaveGameToSlot(Bad,Slot,User));TestEqual(TEXT("bad schema"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::UnsupportedSchema);Profiles->GetProfileSnapshot(TEXT("A"),P);TestEqual(TEXT("failure unchanged"),P.RuntimeState.Experience,0);TestTrue(TEXT("cleanup"),UGameplayStatics::DeleteGameInSlot(Slot,User));return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveDiskFailuresTest,"HSR.Save.DiskFailures",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSRSaveDiskFailuresTest::RunTest(const FString&)
{
	const FString Slot=FString::Printf(TEXT("HSR_P11_FAIL_%s"),*FGuid::NewGuid().ToString(EGuidFormats::Digits));const int32 User=0;UGameplayStatics::DeleteGameInSlot(Slot,User);ON_SCOPE_EXIT{UGameplayStatics::DeleteGameInSlot(Slot,User);};
	UGameInstance* GI=NewObject<UGameInstance>();auto* Profiles=NewObject<UHSRCharacterProfileSubsystem>(GI);auto* Party=NewObject<UHSRPartySubsystem>(GI);auto* Save=NewObject<UHSRSaveSubsystem>(GI);auto* Equipment=NewObject<UHSREquipmentSubsystem>(GI);auto* D=NewObject<UHSRCharacterDefinition>();D->CharacterId=TEXT("A");D->MaxLevel=2;auto* C=NewObject<UCurveFloat>(D);C->FloatCurve.AddKey(2,100);D->CumulativeExperienceCurve=C;Profiles->RegisterDefinition(D);Party->InitializeForDevelopmentTest(Profiles);Save->InitializeForDevelopmentTest(Profiles,Party,Equipment);Party->AddCharacter(TEXT("A"));TestEqual(TEXT("baseline save"),Save->SaveToSlot(Slot,User),EHSRSaveResult::Success);const FHSRSaveData Baseline=Save->GetSnapshot();Profiles->GrantExperience(TEXT("A"),100);Party->RemoveCharacter(0);int32 PE=0,QE=0;Profiles->OnProfileChanged().AddLambda([&](FName,int64){++PE;});Party->OnPartyChanged().AddLambda([&](int64){++QE;});
	auto AssertUnchanged=[&](const TCHAR* Label){FHSRCharacterProfileSnapshot P;FHSRPartySnapshot Q;Profiles->GetProfileSnapshot(TEXT("A"),P);Party->GetSnapshot(Q);TestEqual(Label,P.RuntimeState.Experience,100);TestEqual(TEXT("party revision unchanged"),Q.Revision,static_cast<int64>(2));TestTrue(TEXT("runtime party remains empty"),Q.Slots[0].IsEmpty());TestEqual(TEXT("current revision unchanged"),Save->GetSnapshot().PartyRevision,Baseline.PartyRevision);TestEqual(TEXT("current experience unchanged"),Save->GetSnapshot().Profiles[0].State.Experience,0);TestEqual(TEXT("profile events unchanged"),PE,0);TestEqual(TEXT("party events unchanged"),QE,0);};
	Save->SetDiskFailureInjection(true,false,false);TestEqual(TEXT("inject create"),Save->SaveToSlot(Slot,User),EHSRSaveResult::CreateFailed);AssertUnchanged(TEXT("create profile unchanged"));Save->SetDiskFailureInjection(false,true,false);TestEqual(TEXT("inject save"),Save->SaveToSlot(Slot,User),EHSRSaveResult::SaveFailed);AssertUnchanged(TEXT("save profile unchanged"));const UHSRSaveGame* StillOld=Cast<UHSRSaveGame>(UGameplayStatics::LoadGameFromSlot(Slot,User));TestTrue(TEXT("slot not replaced"),StillOld&&StillOld->Data.PartyRevision==1&&StillOld->Data.Profiles[0].State.Experience==0);Save->SetDiskFailureInjection(false,false,true);TestEqual(TEXT("inject load"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::LoadFailed);AssertUnchanged(TEXT("load profile unchanged"));Save->SetDiskFailureInjection(false,false,false);
	UHSRSaveGame* Bad=Cast<UHSRSaveGame>(UGameplayStatics::CreateSaveGameObject(UHSRSaveGame::StaticClass()));Bad->Data=Baseline;Bad->Data.Profiles[0].State.Level=99;TestTrue(TEXT("write bad dto"),UGameplayStatics::SaveGameToSlot(Bad,Slot,User));TestEqual(TEXT("bad dto disk"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::InvalidData);AssertUnchanged(TEXT("dto profile unchanged"));Bad->Data=Baseline;Bad->Data.SchemaVersion=5;UGameplayStatics::SaveGameToSlot(Bad,Slot,User);TestEqual(TEXT("schema disk"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::UnsupportedSchema);AssertUnchanged(TEXT("schema profile unchanged"));USaveGame* Wrong=UGameplayStatics::CreateSaveGameObject(UHSRForeignSaveGame::StaticClass());UGameplayStatics::SaveGameToSlot(Wrong,Slot,User);TestEqual(TEXT("class disk"),Save->LoadFromSlot(Slot,User),EHSRSaveResult::ClassMismatch);AssertUnchanged(TEXT("class profile unchanged"));TestTrue(TEXT("cleanup delete"),UGameplayStatics::DeleteGameInSlot(Slot,User));TestFalse(TEXT("cleanup absent"),UGameplayStatics::DoesSaveGameExist(Slot,User));return true;
}
#endif
