#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "../Save/HSRSaveVersion.h"
namespace
{
FString Hex(const TArray<uint8>& Bytes){return BytesToHex(Bytes.GetData(),Bytes.Num()).ToLower();}
void Put32(TArray<uint8>& Bytes,int32 Offset,uint32 Value){for(int32 I=0;I<4;++I)Bytes[Offset+I]=static_cast<uint8>(Value>>(I*8));}
void Put64(TArray<uint8>& Bytes,int32 Offset,uint64 Value){for(int32 I=0;I<8;++I)Bytes[Offset+I]=static_cast<uint8>(Value>>(I*8));}
void Resign(TArray<uint8>& Bytes){FMemory::Memset(Bytes.GetData()+72,0,32);TArray<uint8> Digest;HSRSaveVersion::ComputeSha256(Bytes,Digest);FMemory::Memcpy(Bytes.GetData()+72,Digest.GetData(),32);}
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveEnvelopeTest, "HSR.Save.EnvelopeV1", EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)
bool FHSRSaveEnvelopeTest::RunTest(const FString&)
{
	TArray<uint8> Empty,Hash,Abc;TestTrue(TEXT("sha empty"),HSRSaveVersion::ComputeSha256(Empty,Hash));TestEqual(TEXT("sha empty vector"),Hex(Hash),FString(TEXT("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")));Abc.Add('a');Abc.Add('b');Abc.Add('c');TestTrue(TEXT("sha abc"),HSRSaveVersion::ComputeSha256(Abc,Hash));TestEqual(TEXT("sha abc vector"),Hex(Hash),FString(TEXT("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")));
	FHSRSaveData Data; Data.SchemaVersion=6; Data.PartySlots.SetNum(HSRSaveVersion::PartySlotCount); Data.PartySlots[0].CharacterId=TEXT("Character.A"); FHSRSaveProfileDto Profile; Profile.State.CharacterId=TEXT("Character.A"); Data.Profiles.Add(Profile);
	FHSRItemStackSnapshot Stack;Stack.ItemId=TEXT("item.potion");Stack.Quantity=3;Data.Inventory.Stacks.Add(Stack);FHSRItemInstance Unique;Unique.InstanceId=FGuid(7,0,0,1);Unique.DefinitionId=TEXT("item.relic");Data.Inventory.UniqueItems.Add(Unique);Data.Inventory.Revision=2;
	FHSRRewardReceipt Receipt;Receipt.Request.ClaimId=FGuid(8,0,0,1);Receipt.Request.RewardDefinitionId=TEXT("reward.test");Receipt.Request.Seed=42;FHSRInventoryGrant Grant;Grant.ItemId=TEXT("item.potion");Grant.Quantity=2;Grant.InstanceIds.Add(FGuid(9,0,0,1));Receipt.Grants.Add(Grant);Receipt.Revision=3;Data.Rewards.Receipts.Add(Receipt);Data.Rewards.Revision=3;
	FHSRQuestRuntimeState Quest;Quest.QuestId=TEXT("quest.test");Quest.State=EHSRQuestState::Active;FHSRQuestRuntimeObjective Objective;Objective.ObjectiveId=TEXT("objective.one");Objective.CurrentCount=1;Objective.RequiredCount=2;Quest.Objectives.Add(Objective);Quest.Revision=4;Data.Quests.States.Add(Quest);Data.Quests.Revision=4;
	FHSREquipmentSaveDto Equipment;Equipment.DefinitionId=TEXT("equipment.blade");Equipment.InstanceId=FGuid(10,0,0,1);Equipment.CharacterId=FGuid(11,0,0,1);Equipment.Kind=0;Equipment.Slot=static_cast<int32>(EHSREquipmentSlot::Weapon);Equipment.EnhancementLevel=2;FHSREquipmentModifier Modifier;Modifier.Stat=EHSREquipmentStat::Attack;Modifier.Value=1.25f;Equipment.Modifiers.Add(Modifier);Equipment.AuthorityRevision=5;Data.Equipment.Add(Equipment);
	Data.Map.CurrentLocation.MapId=TEXT("map.alpha");Data.Map.CurrentLocation.ArrivalId=TEXT("arrival.entry");Data.Map.CurrentLocation.WorldTransform=FTransform(FRotator(0,45,0),FVector(10,20,30),FVector(1,2,1));Data.Map.UnlockedRegionIds.Add(TEXT("region.one"));Data.Map.UnlockedTeleportIds.Add(TEXT("teleport.one"));Data.Map.ExplorationFlags.Add(TEXT("flag.chest.open"));Data.Map.Revision=6;
	const FGuid Id(1,2,3,4); TArray<uint8> Bytes; TestTrue(TEXT("encode"),HSRSaveVersion::EncodeEnvelope(Data,TEXT("P16_Vector"),0,Id,1,Bytes)); TestTrue(TEXT("header bytes"),Bytes.Num()>104); TestEqual(TEXT("magic H"),Bytes[0],static_cast<uint8>('H')); TestEqual(TEXT("format LE"),Bytes[8],static_cast<uint8>(1)); TestEqual(TEXT("header LE"),Bytes[10],static_cast<uint8>(104));
	TArray<uint8> FixedA,FixedB;TestTrue(TEXT("fixed encode"),HSRSaveVersion::EncodeEnvelopeAtUtc(Data,TEXT("P16_Vector"),0,Id,1,123456789,FixedA));TestTrue(TEXT("fixed deterministic"),HSRSaveVersion::EncodeEnvelopeAtUtc(Data,TEXT("P16_Vector"),0,Id,1,123456789,FixedB));TestTrue(TEXT("golden bytes stable"),FixedA==FixedB);TestEqual(TEXT("fixed timestamp little endian"),FixedA[56],static_cast<uint8>(0x15));TArray<uint8> FixedHash;HSRSaveVersion::ComputeSha256(FixedA,FixedHash);FString FixtureDigest;const FString FixturePath=FPaths::Combine(FPaths::ProjectDir(),TEXT("Source/HSR/Tests/Fixtures/Save/schema-v6-full.sha256"));TestTrue(TEXT("fixture manifest readable"),FFileHelper::LoadFileToString(FixtureDigest,*FixturePath));FixtureDigest.TrimStartAndEndInline();TestEqual(TEXT("full-domain fixture manifest"),Hex(FixedHash),FixtureDigest);TestEqual(TEXT("full-domain cross-process golden"),Hex(FixedHash),FString(TEXT("67a6ec217fd1de71a93ba1b4dd8778ba1079d2ea1009a406e10ab019062fdd75")));TArray<uint8> HeaderPrefix;HeaderPrefix.Append(FixedA.GetData(),72);TestEqual(TEXT("full header 0..71 golden"),Hex(HeaderPrefix),FString(TEXT("4853525341564500010068000600000001000000010000004e0200000000000001000000020000000300000004000000010000000000000015cd5b07000000009401bbd3d995956c")));
	FHSRSaveData Decoded; FHSRSaveEnvelopeHeader Header; TestEqual(TEXT("decode"),HSRSaveVersion::DecodeEnvelope(Bytes,TEXT("P16_Vector"),0,Decoded,&Header),EHSRSaveDecodeResult::Success); TestEqual(TEXT("schema migrated"),Decoded.SchemaVersion,7); TestEqual(TEXT("logical FName"),Decoded.Profiles[0].State.CharacterId,FName(TEXT("Character.A")));TestEqual(TEXT("inventory roundtrip"),Decoded.Inventory.Stacks[0].Quantity,3);TestEqual(TEXT("reward roundtrip"),Decoded.Rewards.Receipts[0].Request.Seed,42);TestEqual(TEXT("quest roundtrip"),Decoded.Quests.States[0].Objectives[0].RequiredCount,2);TestEqual(TEXT("equipment registry roundtrip"),Decoded.EquipmentRegistry[0].EnhancementLevel,2);TestEqual(TEXT("equipment modifier roundtrip"),Decoded.EquipmentRegistry[0].Modifiers[0].Value,1.25f);TestEqual(TEXT("equipment placement roundtrip"),Decoded.EquipmentPlacements[0].InstanceId,Equipment.InstanceId);TestEqual(TEXT("map roundtrip"),Decoded.Map.CurrentLocation.MapId,FName(TEXT("map.alpha")));TestEqual(TEXT("map collection roundtrip"),Decoded.Map.ExplorationFlags[0],FName(TEXT("flag.chest.open")));
	FHSRSaveData InvalidData=Data;InvalidData.Profiles[0].State.CharacterId=NAME_None;TArray<uint8> InvalidBytes;TestFalse(TEXT("required empty rejected by encoder"),HSRSaveVersion::EncodeCanonicalPayload(InvalidData,InvalidBytes));InvalidData=Data;const FHSREquipmentSaveDto DuplicateEquipment=InvalidData.Equipment[0];InvalidData.Equipment.Add(DuplicateEquipment);TestFalse(TEXT("duplicate equipment rejected by encoder"),HSRSaveVersion::EncodeCanonicalPayload(InvalidData,InvalidBytes));InvalidData=Data;InvalidData.Equipment[0].Kind=9;TestFalse(TEXT("invalid equipment enum rejected by encoder"),HSRSaveVersion::EncodeCanonicalPayload(InvalidData,InvalidBytes));InvalidData=Data;const FName DuplicateFlag=InvalidData.Map.ExplorationFlags[0];InvalidData.Map.ExplorationFlags.Add(DuplicateFlag);TestFalse(TEXT("duplicate map id rejected by encoder"),HSRSaveVersion::EncodeCanonicalPayload(InvalidData,InvalidBytes));
	TArray<uint8> Reencoded; TestTrue(TEXT("migrated schema reencodes"),HSRSaveVersion::EncodeCanonicalPayload(Decoded,Reencoded)); TestTrue(TEXT("migrated schema has payload"),!Reencoded.IsEmpty()); Bytes[104]^=1; TestEqual(TEXT("checksum first"),HSRSaveVersion::DecodeEnvelope(Bytes,TEXT("P16_Vector"),0,Decoded),EHSRSaveDecodeResult::ChecksumMismatch);
	FHSRSaveData V1=Data;V1.SchemaVersion=1;TestEqual(TEXT("migration"),HSRSaveVersion::MigrateToCurrent(V1),EHSRSaveDecodeResult::Success);TestEqual(TEXT("v7"),V1.SchemaVersion,7);return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FHSRSaveClassificationTest,"HSR.Save.VersionClassification",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FHSRSaveClassificationTest::RunTest(const FString&)
{
	TestTrue(TEXT("payload max accepted"),HSRSaveVersion::IsValidPayloadSize(FHSRSaveEnvelopeHeader::MaxPayloadBytes));TestFalse(TEXT("payload max plus one rejected"),HSRSaveVersion::IsValidPayloadSize(FHSRSaveEnvelopeHeader::MaxPayloadBytes+1));
	TestTrue(TEXT("record max accepted"),HSRSaveVersion::MaxRecordCount==65535);TestFalse(TEXT("record max plus one fits contract"),static_cast<uint64>(HSRSaveVersion::MaxRecordCount)+1<=HSRSaveVersion::MaxRecordCount);
	TestTrue(TEXT("token max accepted"),HSRSaveVersion::IsCanonicalIdToken(FString::ChrN(HSRSaveVersion::MaxTokenBytes,'a')));TestFalse(TEXT("token max plus one rejected"),HSRSaveVersion::IsCanonicalIdToken(FString::ChrN(HSRSaveVersion::MaxTokenBytes+1,'a')));TestFalse(TEXT("token uppercase rejected"),HSRSaveVersion::IsCanonicalIdToken(TEXT("Character.A")));TestFalse(TEXT("token unicode rejected"),HSRSaveVersion::IsCanonicalIdToken(TEXT("角色.a")));
	FHSRSaveData Data;Data.SchemaVersion=6;Data.PartySlots.SetNum(HSRSaveVersion::PartySlotCount);TArray<uint8> Base;TestTrue(TEXT("baseline"),HSRSaveVersion::EncodeEnvelopeAtUtc(Data,TEXT("p16.class"),2,FGuid(1,2,3,4),7,42,Base));FHSRSaveData Out;
	TestEqual(TEXT("bad argument"),HSRSaveVersion::DecodeEnvelope(Base,TEXT("bad:slot"),2,Out),EHSRSaveDecodeResult::InvalidArgument);
	TArray<uint8> Mut=Base;Mut.SetNum(103);TestEqual(TEXT("too short"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::TooShort);
	Mut=Base;Mut[0]^=1;TestEqual(TEXT("bad magic before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::BadMagic);
	Mut=Base;Mut[8]=2;TestEqual(TEXT("format before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::UnsupportedFormat);
	Mut=Base;Mut[10]=105;TestEqual(TEXT("header size before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::UnsupportedFormat);
	Mut=Base;Mut[20]=2;TestEqual(TEXT("codec before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::UnsupportedFormat);
	Mut=Base;Mut[22]=1;TestEqual(TEXT("flags before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::UnsupportedFormat);
	Mut=Base;FMemory::Memset(Mut.GetData()+32,0,16);TestEqual(TEXT("invalid save id before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::InvalidHeader);
	Mut=Base;Put64(Mut,48,0);TestEqual(TEXT("invalid generation before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::InvalidHeader);
	Mut=Base;Put64(Mut,24,FHSRSaveEnvelopeHeader::MaxPayloadBytes+1);TestEqual(TEXT("size before checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::InvalidSize);
	TArray<uint8> MaxSized;MaxSized.SetNumZeroed(FHSRSaveEnvelopeHeader::HeaderBytes+FHSRSaveEnvelopeHeader::MaxPayloadBytes);FMemory::Memcpy(MaxSized.GetData(),Base.GetData(),FHSRSaveEnvelopeHeader::HeaderBytes);Put64(MaxSized,24,FHSRSaveEnvelopeHeader::MaxPayloadBytes);Resign(MaxSized);TestTrue(TEXT("actual payload max passes size gate"),HSRSaveVersion::DecodeEnvelope(MaxSized,TEXT("p16.class"),2,Out)!=EHSRSaveDecodeResult::InvalidSize);MaxSized.Add(0);Put64(MaxSized,24,FHSRSaveEnvelopeHeader::MaxPayloadBytes+1);TestEqual(TEXT("actual payload max plus one rejected"),HSRSaveVersion::DecodeEnvelope(MaxSized,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::InvalidSize);
	TestEqual(TEXT("slot before checksum"),HSRSaveVersion::DecodeEnvelope(Base,TEXT("p16.other"),2,Out),EHSRSaveDecodeResult::SlotMismatch);
	Mut=Base;Mut[104]^=1;TestEqual(TEXT("checksum"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::ChecksumMismatch);
	Mut=Base;Put32(Mut,12,8);Resign(Mut);TestEqual(TEXT("future"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::FutureSchema);
	Mut=Base;Put32(Mut,12,0);Resign(Mut);TestEqual(TEXT("too old"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::TooOld);
	Mut=Base;Put32(Mut,16,0);Resign(Mut);TestEqual(TEXT("minimum compatible zero"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::InvalidHeader);Mut=Base;Put32(Mut,16,7);Resign(Mut);TestEqual(TEXT("minimum compatible above schema"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::InvalidHeader);
	Mut=Base;Put32(Mut,12,5);Resign(Mut);TestEqual(TEXT("header payload schema mismatch"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::NonCanonical);
	Mut=Base;Mut.Add(0);Put64(Mut,24,Mut.Num()-104);Resign(Mut);TestEqual(TEXT("trailing payload"),HSRSaveVersion::DecodeEnvelope(Mut,TEXT("p16.class"),2,Out),EHSRSaveDecodeResult::InvalidPayload);
	TArray<uint8> CountPayload={6,0,0,0,0xff,0xff,0,0};TestEqual(TEXT("actual count max passes count gate"),HSRSaveVersion::DecodeCanonicalPayload(CountPayload,Out),EHSRSaveDecodeResult::NonCanonical);CountPayload[4]=0;CountPayload[5]=0;CountPayload[6]=1;TestEqual(TEXT("actual count max plus one rejected"),HSRSaveVersion::DecodeCanonicalPayload(CountPayload,Out),EHSRSaveDecodeResult::InvalidPayload);
	FHSRSaveData Future=Data;Future.SchemaVersion=8;TestEqual(TEXT("migrate future"),HSRSaveVersion::MigrateToCurrent(Future),EHSRSaveDecodeResult::FutureSchema);FHSRSaveData Old=Data;Old.SchemaVersion=0;TestEqual(TEXT("migrate old"),HSRSaveVersion::MigrateToCurrent(Old),EHSRSaveDecodeResult::TooOld);FHSRSaveData Invalid=Data;Invalid.PartyRevision=-1;TestEqual(TEXT("post migration validation"),HSRSaveVersion::MigrateToCurrent(Invalid),EHSRSaveDecodeResult::MigrationFailed);
	FHSRSaveData V1=Data;V1.SchemaVersion=1;V1.Equipment.AddDefaulted();V1.Inventory.Revision=9;V1.Rewards.Revision=9;TestEqual(TEXT("v1 migrate"),HSRSaveVersion::MigrateToCurrent(V1),EHSRSaveDecodeResult::Success);TestTrue(TEXT("v1 equipment conservative empty"),V1.Equipment.IsEmpty());TestEqual(TEXT("v1 inventory conservative empty"),V1.Inventory.Revision,static_cast<int64>(0));TestEqual(TEXT("v1 rewards conservative empty"),V1.Rewards.Revision,static_cast<int64>(0));FHSRSaveData V2=Data;V2.SchemaVersion=2;V2.Inventory.Revision=9;V2.Rewards.Revision=9;TestEqual(TEXT("v2 migrate"),HSRSaveVersion::MigrateToCurrent(V2),EHSRSaveDecodeResult::Success);TestEqual(TEXT("v2 inventory conservative empty"),V2.Inventory.Revision,static_cast<int64>(0));TestEqual(TEXT("v2 rewards conservative empty"),V2.Rewards.Revision,static_cast<int64>(0));
	return true;
}
#endif
