#include "HSREquipmentEffectBridge.h"
#include "../GAS/Attribute/HSRCoreAttributeSet.h"
#include "../Progression/HSRProgressionGameplayTags.h"
#include "AbilitySystemComponent.h"
#include "GameplayEffect.h"
bool UHSREquipmentEffectBridge::CanApply(UAbilitySystemComponent* ASC,TSubclassOf<UGameplayEffect> C,const FHSREquipmentAggregate& A) const
{
 if(!ASC||!C||A.Revision<0)return false;
 return ASC->MakeOutgoingSpec(C,1.f,ASC->MakeEffectContext()).IsValid();
}
bool UHSREquipmentEffectBridge::Apply(const FGuid& Key,UAbilitySystemComponent* ASC,TSubclassOf<UGameplayEffect> C,const FHSREquipmentAggregate& A){if(!Key.IsValid()||!ASC||!C||A.Revision<0){UE_LOG(LogTemp,Warning,TEXT("HSR.EquipmentBridge Apply InvalidInput Key=%s ASC=%s Class=%s Revision=%lld"),*Key.ToString(),ASC?*ASC->GetName():TEXT("None"),C?*C->GetName():TEXT("None"),A.Revision);return false;} if(FSource* O=Sources.Find(Key)) if(O->ASC.Get()==ASC&&O->Class==C&&O->Handle.IsValid()&&ASC->GetActiveGameplayEffect(O->Handle)&&O->Fingerprint.MaxHealth==A.MaxHealth&&O->Fingerprint.Attack==A.Attack&&O->Fingerprint.Defense==A.Defense&&O->Fingerprint.Speed==A.Speed){O->Fingerprint.Revision=A.Revision;return true;} const FGameplayEffectSpecHandle S=ASC->MakeOutgoingSpec(C,1.f,ASC->MakeEffectContext()); if(!S.IsValid()){UE_LOG(LogTemp,Warning,TEXT("HSR.EquipmentBridge Apply SpecInvalid Key=%s Class=%s"),*Key.ToString(),*C->GetName());return false;} S.Data->SetSetByCallerMagnitude(HSREquipmentTags::BonusMaxHealth,A.MaxHealth);S.Data->SetSetByCallerMagnitude(HSREquipmentTags::BonusAttack,A.Attack);S.Data->SetSetByCallerMagnitude(HSREquipmentTags::BonusDefense,A.Defense);S.Data->SetSetByCallerMagnitude(HSREquipmentTags::BonusSpeed,A.Speed); FActiveGameplayEffectHandle H=ASC->ApplyGameplayEffectSpecToSelf(*S.Data.Get()); if(!H.WasSuccessfullyApplied()){UE_LOG(LogTemp,Error,TEXT("HSR.EquipmentBridge Apply Failed Key=%s Class=%s Revision=%lld Values=%.3f/%.3f/%.3f/%.3f"),*Key.ToString(),*C->GetName(),A.Revision,A.MaxHealth,A.Attack,A.Defense,A.Speed);return false;} if(FSource* O=Sources.Find(Key)){if(O->ASC.IsValid()&&O->Handle.IsValid()&&O->ASC->GetActiveGameplayEffect(O->Handle)){if(!O->ASC->RemoveActiveGameplayEffect(O->Handle)){ASC->RemoveActiveGameplayEffect(H);UE_LOG(LogTemp,Error,TEXT("HSR.EquipmentBridge Apply OldRemoveFailed Key=%s OldHandle=%s NewHandle=%s"),*Key.ToString(),*O->Handle.ToString(),*H.ToString());return false;}}} FSource Src;Src.ASC=ASC;Src.Class=C;Src.Fingerprint=A;Src.Handle=H;Sources.Add(Key,Src); return true;}
bool UHSREquipmentEffectBridge::Remove(const FGuid& Key){FSource* S=Sources.Find(Key);if(!S){UE_LOG(LogTemp,Warning,TEXT("HSR.EquipmentBridge Remove MissingSource Key=%s"),*Key.ToString());return true;}bool Ok=!S->Handle.IsValid()||!S->ASC.IsValid()||!S->ASC->GetActiveGameplayEffect(S->Handle)||S->ASC->RemoveActiveGameplayEffect(S->Handle);if(Ok)Sources.Remove(Key);else UE_LOG(LogTemp,Error,TEXT("HSR.EquipmentBridge Remove Failed Key=%s Handle=%s ASC=%s"),*Key.ToString(),*S->Handle.ToString(),S->ASC.IsValid()?*S->ASC->GetName():TEXT("None"));return Ok;}
bool UHSREquipmentEffectBridge::RemoveAll(){bool Ok=true; for(auto& P:Sources){if(UAbilitySystemComponent* A=P.Value.ASC.Get()) if(P.Value.Handle.IsValid()&&A->GetActiveGameplayEffect(P.Value.Handle)) Ok=A->RemoveActiveGameplayEffect(P.Value.Handle)&&Ok;} if(Ok){Sources.Empty();SetSourceKeys.Empty();} return Ok;}
bool UHSREquipmentEffectBridge::ApplySetSource(const FName& SetSourceId,UAbilitySystemComponent* ASC,TSubclassOf<UGameplayEffect> EffectClass,const FHSREquipmentAggregate& Aggregate){if(SetSourceId.IsNone())return false; FGuid& Key=SetSourceKeys.FindOrAdd(SetSourceId); if(!Key.IsValid()) Key=FGuid(0,GetTypeHash(SetSourceId),0,1); return Apply(Key,ASC,EffectClass,Aggregate);}
bool UHSREquipmentEffectBridge::RemoveSetSource(const FName& SetSourceId){const FGuid* Key=SetSourceKeys.Find(SetSourceId); if(!Key){UE_LOG(LogTemp,Warning,TEXT("HSR.EquipmentBridge RemoveSetSource MissingSource Set=%s"),*SetSourceId.ToString());return true;} const bool bRemoved=Remove(*Key); if(bRemoved)SetSourceKeys.Remove(SetSourceId); return bRemoved;}
