;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Cooldown",DevComment="")
+GameplayTagList=(Tag="Damage",DevComment="")
+GameplayTagList=(Tag="Damage.Data.AbilityMultiplier",DevComment="P7 execution input")
+GameplayTagList=(Tag="Damage.Data.CritRoll",DevComment="P7 execution input")
+GameplayTagList=(Tag="Damage.Data.DefenseCoefficient",DevComment="P7 execution input")
+GameplayTagList=(Tag="Damage.Data.MinDamage",DevComment="P7 execution input")
+GameplayTagList=(Tag="Damage.Data.ToughnessDamage",DevComment="P8 toughness damage SetByCaller input")
+GameplayTagList=(Tag="Damage.Type.Break",DevComment="")
+GameplayTagList=(Tag="Damage.Type.Physical",DevComment="Phase 7 physical damage rule identifier")
+GameplayTagList=(Tag="Element",DevComment="")
+GameplayTagList=(Tag="Element.Arc",DevComment="")
+GameplayTagList=(Tag="Element.Gale",DevComment="")
+GameplayTagList=(Tag="Element.Tide",DevComment="")
+GameplayTagList=(Tag="Event",DevComment="")
+GameplayTagList=(Tag="State",DevComment="")
+GameplayTagList=(Tag="State.Break",DevComment="")
+GameplayTagList=(Tag="Status",DevComment="")
+GameplayTagList=(Tag="UI",DevComment="")
+GameplayTagList=(Tag="Weakness.Arc",DevComment="")
+GameplayTagList=(Tag="Weakness.Gale",DevComment="")
+GameplayTagList=(Tag="Weakness.Tide",DevComment="")
